[build-system]
requires = ["scikit-build-core", "pybind11", "pybind11-stubgen"]
build-backend = "scikit_build_core.build"

[project]
name = "qsteed"
dynamic = ["version"]
readme = {file = "README.md", content-type = "text/markdown"}
description = "Quantum Software of Compilation for supporting Real Quantum device"
authors = [
    {name = "Xuhongze", email = "xhzby1995@163.com"}
]
license = "Apache-2.0"
license-files = ["LICENSE"]
keywords = ["qsteed", "quantum compiling", "quantum computing", "quantum operating system"]

requires-python = ">=3.10"
dependencies = [
    "dill>=0.3.8",
    "ipython>=8.14.0",
    "matplotlib>=3.5.2",
    "networkx>=2.6.3",
    "numpy>=1.20.3,<2.0.0",
    "Pillow>=10.4.0",
    "graphviz>=0.14.2",
    "rich>=13.7.1",
    "scipy>=1.8.1",
    "tabulate>=0.9.0",
    "sqlalchemy>=2.0.28",
    "flask>=3.0.2",
    "pymysql>=1.1.0",
    "flask_sqlalchemy>=3.1.1",
]


[project.optional-dependencies]
tests = ["pytest"]
torch = ["torch"]

[project.urls]
Homepage = "https://github.com/BAQIS-Quantum/QSteed"
Documentation = "https://github.com/BAQIS-Quantum/QSteed/wiki"
Source = "https://github.com/BAQIS-Quantum/QSteed"
Issues = "https://github.com/BAQIS-Quantum/QSteed/issues"

[project.scripts]
qsteed-config = "qsteed.qsteed_config:copy_config"
qsteed-build-db = "qsteed.first_build_db:first_build_db"

[tool.scikit-build]
cmake.args = ["-DBUILD_WITH_GRAPHVIZ=OFF"]

[tool.scikit-build.metadata.version]
provider = "scikit_build_core.metadata.regex"
input = "qsteed/VERSION.txt"
regex = "(?P<value>.*)"

[tool.cibuildwheel]
manylinux-x86_64-image = "manylinux2014"
manylinux-i686-image = "manylinux2014"
build = "cp310-win_amd64 cp311-win_amd64 cp312-win_amd64"

[tool.cibuildwheel.linux]
repair-wheel-command = "auditwheel repair -w {dest_dir} {wheel}"

[tool.cibuildwheel.macos]
repair-wheel-command = "delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}"

[tool.cibuildwheel.windows]
repair-wheel-command = "cp {wheel} {dest_dir}/."
