[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "qsteed"
dynamic = ["version", "readme", "dependencies"]
description = "Quantum Software of Compilation for supporting Real Quantum device"
authors = [
    {name = "Xuhongze", email = "xhzby1995@163.com"}
]
license = {text = "Apache-2.0"}
keywords = ["qsteed", "quantum compiling", "quantum computing", "quantum operating system"]
requires-python = ">=3.10"

[project.optional-dependencies]
tests = ["pytest"]

[project.urls]
Homepage = "https://github.com/BAQIS-Quantum/QSteed"
Documentation = "https://github.com/BAQIS-Quantum/QSteed/wiki"
Source = "https://github.com/BAQIS-Quantum/QSteed"
Issues = "https://github.com/BAQIS-Quantum/QSteed/issues"

[project.scripts]
qsteed-config = "qsteed.qsteed_config:copy_config"
qsteed-build-db = "qsteed.first_build_db:first_build_db"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["qsteed*"]

[tool.setuptools.dynamic]
version = {file = "qsteed/VERSION.txt"}
readme = {file = "README.md", content-type = "text/markdown"}
dependencies = {file = "requirements.txt"}
