[Database]
# Select database backend: "mysql" or "sqlite".
db_type = "sqlite"
# SQLite file path (used when db_type is "sqlite").
sqlite_config = {"path": "~/QSteed/qsteed.db"}


[MySQL]
mysql_config = {"host": "localhost",
                "user": "root",
                "password": "xhz12345",
                "database": "qsteed-mini"
               }

[Chips]
# Add chip information here. Please keep the dictionary keys unchanged.
example = {"name": "example",
          "qubit_num": 10,
          "system_id": 0,
          "basis_gates": ["cx", "ry", "rz", "rx", "h", "id"]
           }
dongling = {"name": "Dongling",
            "qubit_num": 84,
            "system_id": 2,
            "basis_gates": ["cx", "ry", "rz", "rx", "h", "id"]
           }
shenglian = {"name": "Shenglian",
			"qubit_num": 84,
			"system_id": 15,
			"basis_gates": ["cx", "ry", "rz", "rx", "h", "id"]
			}
hongluo = {"name": "Hongluo",
	"qubit_num": 72,
	"system_id": 17,
	"basis_gates": ["cx", "ry", "rz", "rx", "h", "id"]
	}
baihua = {"name": "Baihua",
	"qubit_num": 156,
	"system_id": 7,
	"basis_gates": ["cx", "ry", "rz", "rx", "h", "id"]
	}



[ChipsShape]
chips_shape = 
	    {
	        "example": {"dimension": 1, "row": 1, "column": 10},
			"Hongluo": {
	            "dimension": 2,
	            "row": 12,
	            "column": 14
	        },
	        "Dongling": {
	            "dimension": 2,
	            "row": 12,
	            "column": 14
	        },
			"Shenglian": {
	            "dimension": 2,
	            "row": 12,
	            "column": 14
	        },
	        "Baihua": {
	            "dimension": 2,
	            "row": 13,
	            "column": 13
	        },
	    }


[Systems]
system_id_name = {
                   "0": "example",
                   "2": "Dongling",
		            "17": "Hongluo",
	                "7": "Baihua",
	                "15": "Shenglian",
                   }

system_name_id = {
                 "example": 0,
                 "dongling": 2,
		         "hongluo": 17,
	             "baihua": 7,
	             "shenglian": 15,
                 }

[system_status]
0 = "Online"
1 = "Busy"
2 = "Maintenance"
3 = "Offline"
