# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Tests
on:
    push:
    pull_request:
        branches: [master]

jobs:
  tests:
    name: ${{ matrix.os }}-tests-Python-${{matrix.python-version}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-14, ubuntu-latest]
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: C++ dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install boost
        brew install graphviz

    - name: C++ dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libboost-all-dev graphviz libgraphviz-dev


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install 'pyquafu==0.4.2'
        if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi

    - name: Install qsteed
      run: CMAKE_BUILD_PARALLEL_LEVEL=4 pip install -e . -v

    - name: Test with pytest
      run: |
        pip install pytest
        pytest tests/test_dag.py
        pytest tests/test_transpiler.py
        pytest tests/test_transpiler_parallelcircuits.py
        pytest tests/test_transpiler_parametercircuit.py
        pytest tests/test_transpiler_visualization.py
        pytest tests/test_unitary_decompose.py
